# Generated by Django 5.1.3 on 2024-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Gallery')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Our_graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='Graduates')),
            ],
            options={
                'verbose_name': 'Наши выпускники',
                'verbose_name_plural': 'Наши выпускники',
            },
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='school_cherecters_count',
            options={'verbose_name': 'Количество учашихся', 'verbose_name_plural': 'Количество учашихся'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
    ]
