# Generated by Django 5.1.3 on 2024-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gallery_our_graduates_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_cherecters_count',
            name='text',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
